### ISSUE TITLE
How to redirect to a Symfony page ?

### ISSUE THREAD

**Issue by xGouley** [PrestaShop/firebaseauthenticator#4]
I need to redirect to backoffice /product/new page.
How to do this?

**Comment by Quetzacoalt91** [comment]
We can currently only redirect to the legacy controller, because of the token in the URL to generate.

I'm will investigate on the Symfony router, to know if there is a way to get an URL with the token.

**Comment by Quetzacoalt91** [comment]
@toutantic & @xGouley, please have a look at #5

**Comment by xGouley** [comment]
I can redirect to a symfony page now, but I didn't find a way to do my initial request: go to the product/NEW page (go in the empty product form to add a new product)

I tried:
&redirect=admin_product_form&redirectOptions=id%3Dnew
&redirect=admin_product_form&redirectOptions=id%3D
&redirect=admin_product_form&redirectOptions=new
&redirect=admin_product_form/new
&redirect=admin_product_form

All these cannot brings me to the right page...
Do you have a tip to succeed?

**Comment by xGouley** [comment]
Aux [tans](http://www.cnrtl.fr/definition/tans) pour moi, je clos de suite...
