### ISSUE TITLE
$user->disabled is not set

### ISSUE THREAD

**Issue by toutantic** [PrestaShop/firebaseauthenticator#7]
Is the user is not disabled in Firebase the property disabled is not set on the json object leading to many errors that polute the logs:

AH01071: Got error 'PHP message: PHP Notice: Undefined property: stdClass::$error in modules/firebaseauthenticator/classes/FirebaseClient.php on line 130
PHP message: PHP Notice: Undefined property: stdClass::$disabled in modules/firebaseauthenticator/controllers/admin/AdminLoginController.php on line 82',
 referer: https://ready.prestashop.com/dashboard

**Comment by Quetzacoalt91** [comment]
This needs more investigation.
I just tested the API with a valid token, and the "disabled" is found:

```json
{
    "kind": "identitytoolkit#GetAccountInfoResponse",
    "users": [
        {
            "localId": "p7GJe2dWTWZSve2vKlm7q0VC3",
            "email": "tho***@prestashop.com",
            "emailVerified": false,
            "providerUserInfo": [
                {
                    "providerId": "password",
                    "federatedId": "tho***@prestashop.com",
                    "email": "tho***@prestashop.com",
                    "rawId": "tho***@prestashop.com"
                }
            ],
            "passwordHash": "UkVENURUQ=",
            "passwordUpdatedAt": 1514383815000,
            "validSince": "1514383815",
            "disabled": false,
            "lastLoginAt": "1514383899000",
            "createdAt": "1514383815000"
        }
    ]
}
```

**Comment by Quetzacoalt91** [comment]
Was fixed by https://github.com/PrestaShop/firebaseauthenticator/pull/10
