### ISSUE TITLE
Use case?

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/firebaseauthenticator#8]
I'm wondering,  where that idea comes from? is there any use case for this module? some SPA applications?

**Comment by Quetzacoalt91** [comment]
This module is currently used with PS Ready (https://www.prestashop.com/en/prestashop-ready), where the main employee account is managed outside PrestaShop. It provides SSO between the shop management and the shop itself.

It catches all login requests try to make them match on a Firebase database. If the login fails, PrestaShop fallbacks on the classic login method.

**Comment by kpodemski** [comment]
Ok, thank you
